### PR TITLE
Update to CocoaPods 1.0

### LINKED ISSUE #48: Migrate to CocoaPods 1.0

### PR DESCRIPTION
**Pull request by astralbodies**
Closes #48 

Modernize the project to use Frameworks everywhere, fix CocoaLumberjack issues, and use CocoaPods 1.0 (rc2 at the moment).

Testing:
1. Install CocoaPods 1.0.0.rc.2 and install pods in the main project and TracksDemo.
2. Build each project.
3. Run TracksDemo.

### CODE REVIEW

**Comment by kwonye** [comment]
@astralbodies are the cocoalumberjack macro warnings ok?

**Comment by astralbodies** [comment]
@kwonye I can set the Podfile to ignore them - but yeah I think they're okay for now

**Comment by kwonye** [comment]
Slightly unrelated, but I can't seem to run tests through Xcode. Can we fix that on this PR please?

**Comment by astralbodies** [comment]
@kwonye I think I've solved it. I had to add a Swift file to the main project to force the bundling of a module map. I also tweaked the Podfile to nest the test target into the main target. Feels weird but I get why it had to be done.

**Comment by kwonye** [comment]
👍 everything works for me locally and travis builds fine so :shipit:

**Comment by astralbodies** [comment]
@jleandroperez Can you give the Mac OS X podspec a whirl with 0.1.0?

**Comment by jleandroperez** [comment]
Building great! Simlpenote OSX [PR Here](https://github.com/Automattic/simplenote-osx/pull/432)

**Pull request merged**
